const ROLES = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
};

const TICKET_STATUS = {
  TO_DO: 'TO_DO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CLOSED: 'CLOSED',
};

const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const TICKET_CATEGORY = {
  BUG: 'BUG',
  FEATURE_REQUEST: 'FEATURE_REQUEST',
  SUPPORT: 'SUPPORT',
  BILLING: 'BILLING',
  TECHNICAL: 'TECHNICAL',
  OTHER: 'OTHER',
};

module.exports = {
  ROLES,
  TICKET_STATUS,
  TICKET_PRIORITY,
  TICKET_CATEGORY,
};
